name: CI/CD to EC2
 
on:
  push:
    branches: [ "QA" ]
 
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
 
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
 
      - name: Build Docker Image
        run: docker build -t anggeloo/microservice-product-search:latest .
 
      - name: Push Docker Image
        run: docker push anggeloo/microservice-product-search:latest
 
  deploy-to-ec2:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # 1) Cambiar al directorio donde está el docker-compose.yml
            cd /home/ubuntu/
            
            # 2) Descargar las últimas imágenes desde Docker Hub
            docker pull anggeloo/microservice-add-product:latest
            docker pull anggeloo/microservice-product-search:latest
            docker pull anggeloo/microservice-product-update:latest
            docker pull anggeloo/microservice-product-delete:latest

            # 3) Detener y eliminar los contenedores previos
            docker-compose down

            # 4) Levantar los nuevos contenedores con las imágenes actualizadas
            docker-compose up -d --remove-orphans